#!/bin/bash
#SBATCH -p generic
#$SLURM_SUBMIT_DIR /lustre/home/idab/malfaro
#Cargar modulos
#source ./set_env.sh
#module purge
#module unuse /dragofs/sw/campus/0.2/modules/all/Core
#module unuse /dragofs/sw/restricted/0.2/modules/all/Core
#sleep 2
module load rama0.3
module load GCC/11.3.0
module load STAR/2.7.10b
#comando STAR para generar genoma
STAR --runMode genomeGenerate --genomeDir genomeStaAurCombined --genomeFastaFiles Sa_NCTC8325_NC_007795.1.fasta --sjdbGTFfile SAcombined.gtf --sjdbGTFtagExonParentTranscript gene_id --genomeSAindexNbases 9 --sjdbOverhang 100 --runThreadN 4
