#!/bin/bash
#SBATCH -p generic
#$SLURM_SUBMIT_DIR /lustre/home/idab/malfaro
#Cargar modulos
#source ./set_env.sh
#module purge
## comando para lanzarlo con 4 cores y 12 de RAM : sbatch -p generic -n 4 --mem=12GB STARrun.sh 
#sleep 2
module load rama0.3
module load GCC/11.3.0
module load STAR/2.7.10b
#comando STAR para mapear genoma
STAR --genomeDir genomeStaAur --readFilesIn SRR26422000_pass_1.fastq.gz SRR26422000_pass_2.fastq.gz --runThreadN 4 --limitBAMsortRAM 1089973029 --readFilesCommand gunzip -c --outFileNamePrefix 0 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate
STAR --genomeDir genomeStaAur --readFilesIn SRR26422001_pass_1.fastq.gz SRR26422001_pass_2.fastq.gz --runThreadN 4 --limitBAMsortRAM 1089973029 --readFilesCommand gunzip -c --outFileNamePrefix 1 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate
STAR --genomeDir genomeStaAur --readFilesIn SRR26422002_pass_1.fastq.gz SRR26422002_pass_2.fastq.gz --runThreadN 4 --limitBAMsortRAM 1089973029 --readFilesCommand gunzip -c --outFileNamePrefix 2 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate
STAR --genomeDir genomeStaAur --readFilesIn SRR26422003_pass_1.fastq.gz SRR26422003_pass_2.fastq.gz --runThreadN 4 --limitBAMsortRAM 1089973029 --readFilesCommand gunzip -c --outFileNamePrefix 3 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate
STAR --genomeDir genomeStaAur --readFilesIn SRR26422004_pass_1.fastq.gz SRR26422004_pass_2.fastq.gz --runThreadN 4 --limitBAMsortRAM 1089973029 --readFilesCommand gunzip -c --outFileNamePrefix 4 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate
STAR --genomeDir genomeStaAur --readFilesIn SRR26422005_pass_1.fastq.gz SRR26422005_pass_2.fastq.gz --runThreadN 4 --limitBAMsortRAM 1089973029 --readFilesCommand gunzip -c --outFileNamePrefix 5 --quantMode GeneCounts --outSAMtype BAM SortedByCoordinate
